###############################
# Github Action to rebase release in to staging-spark-job
###############################
name: Build-Staging-Spark

#controls when the pipeline will trigger
on:
  push:
    branches:
      - release-**
  workflow_dispatch: #allows the job to trigger manually

env:
  #GITHUB_USER: ${{ secrets.ACCESS_TOKEN_USR }}
  #GITHUB_PASS: ${{ secrets.ACCESS_TOKEN_PWD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rebase-staging-spark:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout project repo'
        uses: actions/checkout@v3
        with:
          # token: ${{ secrets.ACCESS_TOKEN_PWD }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 'Checkout staging-spark-job'
        run: |
          git fetch --all
          git checkout staging-spark-job
          git pull origin staging-spark-job
          git status

      - name: Removing [ci-skip] commit before rebase
        run: |
          if [[ -n $(git log -1 | grep '.*\[ci-skip\].*') ]]; then
            echo "Removing [ci-skip] commit before rebase"
            git reset --hard HEAD~1
          fi
        shell: bash

      - name: 'Rebase with release*'
        run: |
          git rebase origin/${GITHUB_REF##*/}
          git status

      - name: 'Push to remote'
        run: git push origin staging-spark-job -f
