# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: K1-github-action-workflows-cover

on:
  workflow_call:

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup GO environment
      run: |
        go mod download
        go get -u golang.org/x/lint/golint
        go get -t .
  
    - name: Lint
      run: |
        golint -set_exit_status ./...

    - name: Vet
      run: |
        go vet ./...

    - name: Run new unit tests
      run: |
        sudo go test ./... -coverprofile coverage.out -covermode count
        sudo go tool cover -func coverage.out

    - name: Set new coverage
      run: |
        newCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "New test coverage : newCoverage %"
        echo "new_coverage=newCoverage" >> "$GITHUB_ENV"

    - name: Checkout PR head
      run: |
        git fetch --all
        git checkout ${{ github.event.pull_request.head.sha }}

    - name: Run current unit tests
      run: |
        sudo go test ./... -coverprofile coverage.out -covermode count
        sudo go tool cover -func coverage.out

    - name: Set current coverage
      run: |
        currentCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "Current test coverage : currentCoverage %"
        echo "current_coverage=currentCoverage" >> "$GITHUB_ENV"

    - name: Compare coverage
      run: |
        echo "Quality Gate: checking test coverage is above threshold ..."
        
        if (( $(echo "${{ env.current_coverage }} ${{ env.new_coverage }}" | awk '{print ($1 > $2)}') )); then
            echo "OK"
        else
            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
            echo "Failed"
            exit 1
        fi