###############################
# Shared GitHub Action to run unit tests on base branch and PR branch, then
# compare test coverage to detect any unwanted dips, which may indicate
# a lack of new unit tests.
###############################

name: K1-github-action-workflows-test-and-compare-coverage

on:
  workflow_call:

jobs:
  pr-branch-unit-tests:
    runs-on: ubuntu-latest
    outputs:
      pr_coverage: ${{ steps.unit-tests.outputs.PR_COVERAGE }}
    steps:
      - name: See branches for debugging
        run: |
          echo "Head Branch is ${{ github.event.pull_request.head.ref }}"
          echo "Commit is ${{ github.event.pull_request.head.sha }}"

      - name: Checkout Head Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'

      - name: Go Vet
        run: go vet -v ./...

      - name: Run Unit Tests And Save Coverage
        id: unit-tests
        run: |
          go test ./... -coverprofile coverage.out -covermode count
          echo "PR_COVERAGE=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')" >> "$GITHUB_OUTPUT"
          echo $PR_COVERAGE

  base-branch-unit-tests:
    runs-on: ubuntu-latest
    outputs:
      base_coverage: ${{ steps.unit-tests.outputs.BASE_COVERAGE }}
    steps:
      - name: See branches for debugging
        run: |
          echo "Base Branch is ${{ github.event.pull_request.base.ref }}"
          echo "Commit is ${{ github.event.pull_request.base.sha }}"

      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'

      - name: Go Vet
        run: go vet -v ./...

      - name: Run Unit Tests And Save Coverage
        id: unit-tests
        run: |
          go test ./... -coverprofile coverage.out -covermode count
          echo "BASE_COVERAGE=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')" >> "$GITHUB_OUTPUT"
          echo $BASE_COVERAGE

  compare-coverage:
    runs-on: ubuntu-latest
    needs: [pr-branch-unit-tests, base-branch-unit-tests]
    steps:
      - name: Compare Coverages
        env:
          PR_COVERAGE: ${{ needs.pr-branch-unit-tests.outputs.pr_coverage }}
          BASE_COVERAGE: ${{ needs.base-branch-unit-tests.outputs.base_coverage }}
        run: |
          echo "Base Coverage: $BASE_COVERAGE %"
          echo "PR Coverage: $PR_COVERAGE %"
          echo "TODO do the math"
