###############################
#Github Actions to verify feature flags
###############################
name: K1-github-action-workflows-verify-feature-flags

#controls when the pipeline will trigger
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

#set environment vars for all jobs
env:
  PROJECT_NAME: ${{ inputs.project-name }}
  GITHUB_USER: ${{ secrets.ACCESS_TOKEN_USR }}
  GITHUB_PASS: ${{ secrets.ACCESS_TOKEN_PWD }}
  CHANGE_TARGET: ${{ github.base_ref }} #the target of the merge/pull request
  BRANCH_NAME: ${{ github.head_ref }} #the origin/source of the merge/pull request
  KODDI_PROJECT_KEY: ${{ secrets.KODDI_PROJECT_KEY }}
  LAUNCH_DARKLY_API_KEY: ${{ secrets.LAUNCH_DARKLY_API_KEY }}
  ENV_TO_CHECK: ${{ secrets.ENV_TO_CHECK }}
  ENV_TO_CHECK_AGAINST: ${{ secrets.ENV_TO_CHECK_AGAINST }}


jobs:

  ####################################
  # Runs verify feature flags script. Runs only on PR when targeted branch is master.
  # If fails,this whole pipeline fails. Then Github would mark this PR not mergeable.
  ####################################
  verify-feature-flags:
    runs-on: ubuntu-latest

    steps:

    # checkout the repo
    - name: Checkout project repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Precheck k1
      run: |
        pwd
        ls -l
        whoami
        git status

    - name: Checkout jenkinsfile repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN_PWD }}
        fetch-depth: 1
        repository: KoddiDevTest/Jenkinsfiles-test
        ref: main
        path: jenkins-scripts
        
    - name: Postcheck k1
      run: |
        pwd
        ls -l
        ls -l jenkins-scripts
        whoami
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "PROJECT_NAME: $PROJECT_NAME"
        git status

    # set up node
    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Running feature flag check
      run: |
        node ./jenkins-scripts/scripts/verify-feature-flags-compiled.js


